// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rkpxhfigmeqicnxfvbyr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJrcHhoZmlnbWVxaWNueGZ2YnlyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUxNzIzMjgsImV4cCI6MjA3MDc0ODMyOH0.9oEbfWegUO63oXWnyP-Hv8bVTonNhIHsdVuZRiQT5dg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});